# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SyncGraph.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_syncGraphMainWindow(object):
    def setupUi(self, syncGraphMainWindow):
        syncGraphMainWindow.setObjectName("syncGraphMainWindow")
        syncGraphMainWindow.resize(1024, 875)
        syncGraphMainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        self.centralwidget = QtWidgets.QWidget(syncGraphMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainOptionsBar = QtWidgets.QStackedWidget(self.centralwidget)
        self.mainOptionsBar.setMinimumSize(QtCore.QSize(300, 0))
        self.mainOptionsBar.setMaximumSize(QtCore.QSize(300, 16777215))
        self.mainOptionsBar.setObjectName("mainOptionsBar")
        self.mainOptionsBarPage1 = QtWidgets.QWidget()
        self.mainOptionsBarPage1.setObjectName("mainOptionsBarPage1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainOptionsBarPage1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inFilesToolButtonsLayout = QtWidgets.QHBoxLayout()
        self.inFilesToolButtonsLayout.setObjectName("inFilesToolButtonsLayout")
        self.addInFileButton = QtWidgets.QToolButton(self.mainOptionsBarPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addInFileButton.sizePolicy().hasHeightForWidth())
        self.addInFileButton.setSizePolicy(sizePolicy)
        self.addInFileButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.addInFileButton.setFont(font)
        self.addInFileButton.setObjectName("addInFileButton")
        self.inFilesToolButtonsLayout.addWidget(self.addInFileButton)
        self.removeInFileButton = QtWidgets.QToolButton(self.mainOptionsBarPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeInFileButton.sizePolicy().hasHeightForWidth())
        self.removeInFileButton.setSizePolicy(sizePolicy)
        self.removeInFileButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.removeInFileButton.setFont(font)
        self.removeInFileButton.setObjectName("removeInFileButton")
        self.inFilesToolButtonsLayout.addWidget(self.removeInFileButton)
        self.verticalLayout.addLayout(self.inFilesToolButtonsLayout)
        self.inFilesListView = QtWidgets.QListView(self.mainOptionsBarPage1)
        self.inFilesListView.setToolTipDuration(0)
        self.inFilesListView.setEditTriggers(QtWidgets.QAbstractItemView.CurrentChanged|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.inFilesListView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.inFilesListView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.inFilesListView.setObjectName("inFilesListView")
        self.verticalLayout.addWidget(self.inFilesListView)
        self.loadButton = QtWidgets.QPushButton(self.mainOptionsBarPage1)
        self.loadButton.setMinimumSize(QtCore.QSize(0, 40))
        self.loadButton.setObjectName("loadButton")
        self.verticalLayout.addWidget(self.loadButton)
        self.shiftsGroupBox = QtWidgets.QGroupBox(self.mainOptionsBarPage1)
        self.shiftsGroupBox.setObjectName("shiftsGroupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.shiftsGroupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.shiftsScrollArea = QtWidgets.QScrollArea(self.shiftsGroupBox)
        self.shiftsScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.shiftsScrollArea.setLineWidth(1)
        self.shiftsScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.shiftsScrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.shiftsScrollArea.setWidgetResizable(True)
        self.shiftsScrollArea.setObjectName("shiftsScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 274, 91))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.shiftsScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_5.addWidget(self.shiftsScrollArea, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.shiftsGroupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.mainOptionsBarPage1)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.tstrtEdit = QtWidgets.QSpinBox(self.groupBox_3)
        self.tstrtEdit.setMinimumSize(QtCore.QSize(100, 28))
        self.tstrtEdit.setMaximum(65535)
        self.tstrtEdit.setObjectName("tstrtEdit")
        self.gridLayout_2.addWidget(self.tstrtEdit, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.LEdit = QtWidgets.QSpinBox(self.groupBox_3)
        self.LEdit.setMinimumSize(QtCore.QSize(100, 28))
        self.LEdit.setMinimum(1)
        self.LEdit.setMaximum(65535)
        self.LEdit.setProperty("value", 2000)
        self.LEdit.setObjectName("LEdit")
        self.gridLayout_2.addWidget(self.LEdit, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.LstdEdit = QtWidgets.QSpinBox(self.groupBox_3)
        self.LstdEdit.setMaximum(65535)
        self.LstdEdit.setProperty("value", 150)
        self.LstdEdit.setObjectName("LstdEdit")
        self.gridLayout_2.addWidget(self.LstdEdit, 4, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.mainOptionsBarPage1)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 3, 0, 1, 1)
        self.Fpass2Edit = QtWidgets.QSpinBox(self.groupBox_2)
        self.Fpass2Edit.setMinimumSize(QtCore.QSize(100, 28))
        self.Fpass2Edit.setProperty("value", 35)
        self.Fpass2Edit.setObjectName("Fpass2Edit")
        self.gridLayout_3.addWidget(self.Fpass2Edit, 2, 1, 1, 1)
        self.Fpass1Edit = QtWidgets.QSpinBox(self.groupBox_2)
        self.Fpass1Edit.setMinimumSize(QtCore.QSize(100, 28))
        self.Fpass1Edit.setProperty("value", 20)
        self.Fpass1Edit.setObjectName("Fpass1Edit")
        self.gridLayout_3.addWidget(self.Fpass1Edit, 0, 1, 1, 1)
        self.dfEdit = QtWidgets.QSpinBox(self.groupBox_2)
        self.dfEdit.setProperty("value", 5)
        self.dfEdit.setObjectName("dfEdit")
        self.gridLayout_3.addWidget(self.dfEdit, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.mainOptionsBarPage1)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.extraFUPCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.extraFUPCheckBox.setChecked(True)
        self.extraFUPCheckBox.setObjectName("extraFUPCheckBox")
        self.gridLayout_4.addWidget(self.extraFUPCheckBox, 1, 0, 1, 2)
        self.levEdit = QtWidgets.QSpinBox(self.groupBox_4)
        self.levEdit.setMinimumSize(QtCore.QSize(100, 28))
        self.levEdit.setObjectName("levEdit")
        self.gridLayout_4.addWidget(self.levEdit, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.modeGroupBox = QtWidgets.QGroupBox(self.mainOptionsBarPage1)
        self.modeGroupBox.setObjectName("modeGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.modeGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.debuggingRadioButton = QtWidgets.QRadioButton(self.modeGroupBox)
        self.debuggingRadioButton.setChecked(True)
        self.debuggingRadioButton.setObjectName("debuggingRadioButton")
        self.verticalLayout_3.addWidget(self.debuggingRadioButton)
        self.unloadingRadioButton = QtWidgets.QRadioButton(self.modeGroupBox)
        self.unloadingRadioButton.setObjectName("unloadingRadioButton")
        self.verticalLayout_3.addWidget(self.unloadingRadioButton)
        self.horizontalLayout_2.addWidget(self.modeGroupBox)
        self.buildButton = QtWidgets.QPushButton(self.mainOptionsBarPage1)
        self.buildButton.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.buildButton.setFont(font)
        self.buildButton.setObjectName("buildButton")
        self.horizontalLayout_2.addWidget(self.buildButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.exportButton = QtWidgets.QPushButton(self.mainOptionsBarPage1)
        self.exportButton.setMinimumSize(QtCore.QSize(0, 40))
        self.exportButton.setObjectName("exportButton")
        self.verticalLayout.addWidget(self.exportButton)
        self.mainOptionsBar.addWidget(self.mainOptionsBarPage1)
        self.mainOptionsBarPage2 = QtWidgets.QWidget()
        self.mainOptionsBarPage2.setObjectName("mainOptionsBarPage2")
        self.mainOptionsBar.addWidget(self.mainOptionsBarPage2)
        self.horizontalLayout.addWidget(self.mainOptionsBar)
        self.chooseItemBar = QtWidgets.QFrame(self.centralwidget)
        self.chooseItemBar.setMaximumSize(QtCore.QSize(150, 16777215))
        self.chooseItemBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chooseItemBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chooseItemBar.setObjectName("chooseItemBar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.chooseItemBar)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.chooseItemBar)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.sensorsListView = QtWidgets.QListView(self.chooseItemBar)
        self.sensorsListView.setObjectName("sensorsListView")
        self.verticalLayout_2.addWidget(self.sensorsListView)
        self.horizontalLayout.addWidget(self.chooseItemBar)
        self.tabView = QtWidgets.QTabWidget(self.centralwidget)
        self.tabView.setObjectName("tabView")
        self.graphTabPage = QtWidgets.QWidget()
        self.graphTabPage.setObjectName("graphTabPage")
        self.gridLayout = QtWidgets.QGridLayout(self.graphTabPage)
        self.gridLayout.setObjectName("gridLayout")
        self.graphsContainer = QtWidgets.QWidget(self.graphTabPage)
        self.graphsContainer.setObjectName("graphsContainer")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.graphsContainer)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout.addWidget(self.graphsContainer, 0, 0, 1, 1)
        self.tabView.addTab(self.graphTabPage, "")
        self.tableTabPage = QtWidgets.QWidget()
        self.tableTabPage.setObjectName("tableTabPage")
        self.tabView.addTab(self.tableTabPage, "")
        self.horizontalLayout.addWidget(self.tabView)
        syncGraphMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(syncGraphMainWindow)
        self.tabView.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(syncGraphMainWindow)

    def retranslateUi(self, syncGraphMainWindow):
        _translate = QtCore.QCoreApplication.translate
        syncGraphMainWindow.setWindowTitle(_translate("syncGraphMainWindow", "Graphics synchronization"))
        self.addInFileButton.setText(_translate("syncGraphMainWindow", "+"))
        self.removeInFileButton.setText(_translate("syncGraphMainWindow", "-"))
        self.loadButton.setText(_translate("syncGraphMainWindow", "Load checked files"))
        self.shiftsGroupBox.setTitle(_translate("syncGraphMainWindow", "dT (each file shifts)"))
        self.groupBox_3.setTitle(_translate("syncGraphMainWindow", "Window"))
        self.label_2.setText(_translate("syncGraphMainWindow", "L ( lenght)"))
        self.label.setText(_translate("syncGraphMainWindow", "tstrt (start)"))
        self.label_6.setText(_translate("syncGraphMainWindow", "Lstd (for std, reports)"))
        self.groupBox_2.setTitle(_translate("syncGraphMainWindow", "Frequency"))
        self.label_5.setText(_translate("syncGraphMainWindow", "Fpass2 (end)"))
        self.label_4.setText(_translate("syncGraphMainWindow", "Fpass1 (start)"))
        self.label_9.setText(_translate("syncGraphMainWindow", "df (filter width)"))
        self.Fpass2Edit.setSuffix(_translate("syncGraphMainWindow", " Hz"))
        self.Fpass1Edit.setSuffix(_translate("syncGraphMainWindow", " Hz"))
        self.dfEdit.setSuffix(_translate("syncGraphMainWindow", " Hz"))
        self.groupBox_4.setTitle(_translate("syncGraphMainWindow", "Other"))
        self.label_7.setText(_translate("syncGraphMainWindow", "lev (incoming signal noise level)"))
        self.extraFUPCheckBox.setText(_translate("syncGraphMainWindow", "extraFUP (apply narrowband interference)"))
        self.levEdit.setSuffix(_translate("syncGraphMainWindow", " %"))
        self.modeGroupBox.setTitle(_translate("syncGraphMainWindow", "Mode (compiling mode)"))
        self.debuggingRadioButton.setText(_translate("syncGraphMainWindow", "debugging"))
        self.unloadingRadioButton.setText(_translate("syncGraphMainWindow", "unloading"))
        self.buildButton.setText(_translate("syncGraphMainWindow", "Build"))
        self.exportButton.setText(_translate("syncGraphMainWindow", "Export"))
        self.label_3.setText(_translate("syncGraphMainWindow", "Choose a sensor below"))
        self.tabView.setTabText(self.tabView.indexOf(self.graphTabPage), _translate("syncGraphMainWindow", "Graph"))
        self.tabView.setTabText(self.tabView.indexOf(self.tableTabPage), _translate("syncGraphMainWindow", "Table"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    syncGraphMainWindow = QtWidgets.QMainWindow()
    ui = Ui_syncGraphMainWindow()
    ui.setupUi(syncGraphMainWindow)
    syncGraphMainWindow.show()
    sys.exit(app.exec_())
